---
title: "Species Distribution Modeling"
author: "Peter Menzies"
date: "1/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

librarian::shelf(
  dismo, dplyr, DT, ggplot2, here, htmltools, leaflet, mapview, purrr, raster, readr, rgbif, rgdal, rJava, sdmpredictors, sf, spocc, tidyr)

# library(geojsonio)

select <- dplyr::select # overwrite raster::select

# set random seed for reproducibility
set.seed(42)

# directory to store data
dir_data <- here("data/sdm")
dir.create(dir_data)

redo <- FALSE
```



```{r}
obs_csv <- file.path(dir_data, "obs.csv")
obs_geo <- file.path(dir_data, "obs.geojson")

# get species occurrence data from GBIF with coordinates
if (!file.exists(obs_geo) | redo){
  (res <- spocc::occ(
    query = 'Nomascus gabriellae', 
    from = 'gbif', 
    has_coords = T,
    limit = 10000))

  df <- res$gbif$data[[1]] 
  nrow(df) # number of rows
  
  obs <- df %>% 
    sf::st_as_sf(
      coords = c("longitude", "latitude"),
      crs = st_crs(4326))
  
  readr::write_csv(df, obs_csv)
  
  geojson_write(obs, geometry = "point", file = obs_geo)
}

obs <- sf::read_sf(obs_geo)
nrow(obs) # number of rows
```

```{r}
  # Removing observation of a preserved specimen
  obs <- obs %>% 
    filter(basisOfRecord != "PRESERVED_SPECIMEN")
```


```{r}
# show points on map
mapview::mapview(obs, map.types = "Stamen.Terrain")
```


```{r}
dir_env <- file.path(dir_data, "env")

# set a default data directory
options(sdmpredictors_datadir = dir_env)

# choosing terrestrial
env_datasets <- sdmpredictors::list_datasets(terrestrial = TRUE, marine = FALSE)

# show table of datasets
env_datasets %>% 
  select(dataset_code, description, citation) %>% 
  DT::datatable()
```


```{r}
# choose datasets for a vector
env_datasets_vec <- c("WorldClim", "ENVIREM")

# get layers
env_layers <- sdmpredictors::list_layers(env_datasets_vec)
DT::datatable(env_layers)
```


```{r}
# choose layers after some inspection and perhaps consulting literature
env_layers_vec <- c("WC_alt", "WC_bio1", "WC_bio2", "WC_bio6", "ER_tri", "ER_topoWet")

# get layers
env_stack <- load_layers(env_layers_vec)

# interactive plot layers, hiding all but first (select others)
plot(env_stack, nc = 2)
```


```{r}
obs_hull_geo <- file.path(dir_data, "obs_hull.geojson")
env_stack_grd <- file.path(dir_data, "env_stack.grd")

if (!file.exists(obs_hull_geo) | redo){
  # make convex hull around points of observation
  obs_hull <- sf::st_convex_hull(st_union(obs))
  
  # add buffer to allow more area for random absence points
  obs_hull_buffer <- st_buffer(obs_hull, 50000)
  
  # save obs hull
  write_sf(obs_hull_buffer, obs_hull_geo)
}
obs_hull <- read_sf(obs_hull_geo)

# show points on map
mapview(
  list(obs, obs_hull))
```



```{r}
obs_hull_sp <- sf::as_Spatial(obs_hull)

# cropping env raster stack to extent of convex hull
env_stack <- raster::mask(env_stack, obs_hull_sp) %>%
  raster::crop(extent(obs_hull_sp))

writeRaster(env_stack, env_stack_grd, overwrite = TRUE)

mapview(obs) +
  mapview(env_stack, hide = T)
```


```{r}
if (!file.exists(env_stack_grd) | redo){
  obs_hull_sp <- sf::as_Spatial(obs_hull)
  env_stack <- raster::mask(env_stack, obs_hull_sp) %>% 
    raster::crop(extent(obs_hull_sp))
  writeRaster(env_stack, env_stack_grd, overwrite=T)  
}
env_stack <- stack(env_stack_grd)

# show map
# mapview(obs) + 
#   mapview(env_stack, hide = T) # makes html too big for Github
plot(env_stack, nc = 2)
```


```{r}
absence_geo <- file.path(dir_data, "absence.geojson")
pts_geo     <- file.path(dir_data, "pts.geojson")
pts_env_csv <- file.path(dir_data, "pts_env.csv")

if (!file.exists(absence_geo) | redo){
# get raster count of observations
  r_obs <- obs %>% 
    sf::as_Spatial() %>% 
    rasterize(y = env_stack[[1]], field = 1, fun = 'count')
  
  # mapview(obs) + 
  #   mapview(r_obs)
  
  # create a mask representing locations where the species was NOT observed (inverse=TRUE) within the bounds of the raster stack
  # using the logical "> -Inf" gives us values of 1 for all values in the first stack layer - we only need present / absent
  r_mask <- mask(x = env_stack[[1]] > -Inf, mask = r_obs, inverse = TRUE)
  
  # creating random pseudo-absence points within the mask we just created
  # because of the relatively small spatial scope and the large number of observations within it, trying to create the same number of absence points as there are observations gives us a point in every pixel from the raster, so it's no longer really random... is this an issue?
  absence <- dismo::randomPoints(r_mask, nrow(obs)) %>% 
    as_tibble() %>% 
    st_as_sf(coords = c("x", "y"), crs = 4326)
  
  write_sf(absence, absence_geo, delete_dsn = TRUE)
}
absence <- read_sf(absence_geo)

mapview(obs, col.regions = "green") + 
  mapview(absence, col.regions = "gray")
```

```{r}
if (!file.exists(pts_env_csv) | redo) {
  
  # create combined df of points with absence and presence represented by 0 and 1 respectively in "present" column
  pts <- rbind(
    obs %>% 
      mutate(
        present = 1) %>% 
      select(present),
    absence %>% 
      mutate(
        present = 0)) %>% 
    mutate(
      ID = 1:n()) %>% 
    relocate(ID)
  
  write_sf(pts, pts_geo)
  
  # extract raster values from env_stack where those layers coincide with 'pts'
  pts_env <- raster::extract(env_stack, as_Spatial(pts), df=TRUE) %>% 
    tibble() %>% 
    # join present and geometry columns to raster value results for points
    left_join(
      pts %>% 
        select(ID, present),
      by = "ID") %>% 
    relocate(present, .after = ID) %>% 
    # extract lon, lat as single columns
    mutate(
      #present = factor(present),
      lon = st_coordinates(geometry)[,1],
      lat = st_coordinates(geometry)[,2]) %>% 
    select(-geometry)
  
  write_csv(pts_env, pts_env_csv)
}

pts_env <- read_csv(pts_env_csv)

pts_env %>% 
  # show first 10 presence, last 10 absence
  slice(c(1:10, (nrow(pts_env)-9):nrow(pts_env))) %>% 
  DT::datatable(
    rownames = F,
    options = list(
      dom = "t",
      pageLength = 20))
```


```{r}
pts_env %>% 
  select(-ID) %>% 
  mutate(
    present = factor(present)) %>% 
  pivot_longer(-present) %>% 
  ggplot() +
  geom_density(aes(x = value, fill = present)) + 
  scale_fill_manual(values = alpha(c("gray", "green"), 0.5)) +
  scale_x_continuous(expand=c(0,0)) +
  scale_y_continuous(expand=c(0,0)) +
  theme_bw() + 
  facet_wrap(~name, scales = "free") +
  theme(
    legend.position = c(1, 0),
    legend.justification = c(1, 0))
```







